run:
  deadline: 240s
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - golint
    - varcheck
    - structcheck
    - errcheck
    - staticcheck
    - ineffassign
    - unconvert
    - goimports
    - misspell
    - lll
    - nakedret
    - gocritic
